### ISSUE TITLE
ISSUE 6: Orthographe et formulation de phrase

### ISSUE THREAD

**Issue by Erdnaxela45** [WildCodeSchool/orleans-php-202103-project-clubimmo#146]
- RECHERCHE -> après une sélection amenant à n'avoir aucun résultat, la phrase "Nous sommes désolé. Etc..." n'est pas bien orthographiée/mal formulée
- GLOBAL -> A vendre et A louer nécessitent des accents graves
- CONTACT -> Manque un espace, characters est écrit en anglais lors de l'erreur +255 characters dans l'input message + certaines phrases d'erreurs ont des points à la fin, d'autres non
- CONTACT -> Le bouton d'envoi serait plus clair écrit "Envoyer" plutôt que "Envoyez"

**Comment by jfillion12394** [comment]
erreurs résolues
